# configMap을 YAML로 선언하기

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  hello: world
  kuber: netes
  multiline: |-
    first
    second
    third

# 기존 configmap 삭제
# kubectl delete cm/my-config
#
# configmap 생성
# kubectl apply -f config-map.yml
#
# alpine에 적용
# kubectl apply -f alpine.yml
