apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --watch-ingress-without-class=true
      # - op: add
      #   path: /spec/template/spec/containers/0/args/-
      #   value: --publish-status-address=localhost
      # NOTE: kind Cluster에서 control plane에만 Port Binding이 되어있어서 해당 Node에만 Ingress Controller가 배포되도록 설정
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: "kind-cluster-control-plane"
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule

#   - target:
#       kind: Deployment
#       name: ingress-nginx-controller
#     patch: |-
#       - op: add
#         path: /spec/template/spec/containers/0/args/-
#         value: --enable-ssl-passthrough=true
# - target:
#     kind: ConfigMap
#     name: ingress-nginx-controller
#   patch: |-
#     - op: replace
#       path: /data/allow-snippet-annotations
#       value: "true"
