apiVersion: v1
kind: Pod
metadata:
  name: count
spec:
  volumes:
  - name: html
    emptyDir: {}

  containers:
  - name: html-generator
    image: iamjjanga/count
    volumeMounts:
    - mountPath: /var/htdocs
      name: html

  - name: web-server
    image: httpd
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
