apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    version: 4.12.0
    # includeCRDs: true # ERROR: ensure CRDs are installed first
    valuesFile: values.yaml
