apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    name: http-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hostpath-httpd
  template:
    metadata:
      labels:
        name: hostpath-httpd
    spec:
      containers:
      - image: httpd
        name: web-server
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: html
        hostPath:
          path: /var/htdocs
          type: Directory
