apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    controller:
      config:
        allow-snippet-annotations: "true"
        annotations-risk-level: "Critical"
      nodeSelector:
        kubernetes.io/hostname: "kind-cluster-control-plane" # NOTE: kind Cluster에서 control plane에만 Port Binding이 되어있어서 해당 Node에만 Ingress Controller가 배포되도록 설정
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
