#!/bin/bash

# NOTE: the kind.local+1.pem and kind.local+1-key.pem files are generated by the `mkcert` tool

kubectl create secret tls kind-local-certs --key=kind.local+1-key.pem --cert=kind.local+1.pem
kubectl annotate secret kind-local-certs kubed.appscode.com/sync="" --overwrite