apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: jenkins-ns
spec: {}
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
